// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLocalAuth = `-- name: CreateLocalAuth :exec
INSERT INTO local_auth (member_id, password_hash)
VALUES ($1, $2)
`

type CreateLocalAuthParams struct {
	MemberID     uuid.UUID `json:"member_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateLocalAuth(ctx context.Context, arg CreateLocalAuthParams) error {
	_, err := q.db.Exec(ctx, createLocalAuth, arg.MemberID, arg.PasswordHash)
	return err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (email, data)
VALUES ($1, $2)
RETURNING id, email, data, email_verified_at, created_at, updated_at
`

type CreateMemberParams struct {
	Email string     `json:"email"`
	Data  pgtype.Map `json:"data"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.Email, arg.Data)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Data,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByEmail = `-- name: GetMemberByEmail :one
SELECT id, email, data, email_verified_at, created_at, updated_at FROM members
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetMemberByEmail(ctx context.Context, email string) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByEmail, email)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Data,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberById = `-- name: GetMemberById :one
SELECT id, email, data, email_verified_at, created_at, updated_at FROM members
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMemberById(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberById, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Data,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberWithPassword = `-- name: GetMemberWithPassword :one
SELECT 
    m.id, m.email, m.data, m.email_verified_at, m.created_at, m.updated_at, 
    la.password_hash 
FROM members m
INNER JOIN local_auth la ON m.id = la.member_id
WHERE m.email = $1 LIMIT 1
`

type GetMemberWithPasswordRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	Data            pgtype.Map         `json:"data"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PasswordHash    string             `json:"password_hash"`
}

func (q *Queries) GetMemberWithPassword(ctx context.Context, email string) (GetMemberWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, getMemberWithPassword, email)
	var i GetMemberWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Data,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}
