// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LocalAuth struct {
	MemberID     pgtype.UUID `json:"member_id"`
	PasswordHash string      `json:"password_hash"`
}

type Member struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	Data            pgtype.Map         `json:"data"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}
